name: $(Rev:r)

variables:
  Major: 0
  Minor: 1
  Patch: $[counter(format('{0}.{1}', variables['Major'], variables['Minor'], 0))]
  Version: '$(Major).$(Minor).$(Patch)-preview'
  
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - library
    - tests
    - sporq.nuspec
    - azure-pipeline-build-nuget-ci.yml

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Sporq.nuspec'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Version'

- task: NuGetCommand@2
  displayName: Push Pester Tests NuGet Package to Azure Artifacts
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '71066ab8-a939-4a71-9017-5e0cb4d2f99c'