trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - sporq.nuspec
    - azure-pipeline-build-nuget-ci.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.1'
    checkLatest: true
- task: NuGetCommand@2
  displayName: Pack NuGet package
  inputs:
    command: 'pack'
    packagesToPack: 'Sporq.nuspec'
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget feed connection'