name: public nuget pack, push

on:
  push:
    paths:
    - 'Sporq/Sporq.psd1'
    - '.github/workflows/main-nuget-pub.yml'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Try Powershell
      run: Write-Host "Hello World"
      shell: pwsh
