name: public nuget pack, push

on:
  push:
    paths:
    - 'Sporq/Sporq.psd1'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Run some powershell
      run: pwsh Write-Host "Hello World"
