name: Create Module, Push to Powershell Gallery

on:
  push:
    paths:
    - 'Sporq/Sporq.psd1'
    - '.github/workflows/main-nuget-pub.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Module, Push to Gallery
      run: |
        Import-Module ./Sporq/Sporq.psd1
        Publish-Module -Name 'Sporq' -NuGetApiKey '${{ secrets.sporq_powershell_gallery_api_key }}'
      shell: pwsh
