name: Create Module, Push to Powershell Gallery

on:
  push:
    paths:
    - 'Sporq/Sporq.psd1'
    - '.github/workflows/main-nuget-pub.yml'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Create Module, Push to Gallery
      run: |
        Write-Host "Hello World"
        Import-Module ./Sporq/Sporq.psd1
        Publish-Module -Name 'Sporq' -NuGetApiKey
        Write-Host "Hello World2"
      shell: pwsh
