name: Create Module, Push to Powershell Gallery

on:
  push:
    paths:
    - 'Sporq/Sporq.psd1'
    - '.github/workflows/main-nuget-pub.yml'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Try Powershell
      run: |
        Write-Host "Hello World"
        Write-Host "Hello World2"
      shell: pwsh
